// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations run over Neon's direct (non-pooled) connection.
    // The app's runtime client uses the pooled DATABASE_URL via @prisma/adapter-neon instead.
    url: process.env["DIRECT_URL"],
  },
});
